export const TEAMS_FETCH_REQUESTED:string = 'TEAMS_FETCH_REQUESTED';
export const TEAMS_FETCH_SUCESSFULL:string = 'TEAMS_FETCH_SUCESSFULL';
export const TEAMS_FETCH_FAIL:string = 'TEAMS_FETCH_FAIL';

export const TEAM_FETCH_REQUESTED:string = 'TEAM_FETCH_REQUESTED';
export const TEAM_DETAILS_FETCH_SUCESSFULL:string = 'TEAM_DETAILS_FETCH_SUCESSFULL';
export const TEAM_DETAILS_FETCH_FAIL:string = 'TEAM_DETAILS_FETCH_FAIL';

export const TEAM_MATCHES_FETCH_REQUESTED:string = 'TEAM_MATCHES_FETCH_REQUESTED';
export const TEAM_MATCHES_FETCH_SUCESSFULL:string = 'TEAM_MATCHES_FETCH_SUCESSFULL';
export const TEAM_MATCHES_FETCH_FAIL:string = 'TEAM_MATCHES_FETCH_FAIL';